# (Parte 2) try e except para tratar exceções
# a = 18
# b = 0
# c = a / b

try:
    a = 18
    b = 0
    # print(b[0])
    # print('Linha 1'[1000])
    c = a / b
    print('Linha 2')

except Exception as error:
    print('MSG: ',error)
    print('Error: ',error.__class__.__name__)

print('CONTINUAR')